// IMPU_DATA — Dados dos municípios de Mato Grosso
export const IMPU_DATA: Record<string, CidadeData> = {
  "Acorizal": { macro: "Centro-Sul", pop: 4948, faixaPop: "< 20.000", turismo: false, responsavel: "Diego Emanoel Fernandes Ribeiro", cargo: "Secretaria Municipal de Obras", telefone: "(65) 3353-1203", email: "gabinete@acorizal.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Água Boa": { macro: "Nordeste", pop: 32099, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: "controleinterno@aguaboa.mt.gov.br", pd: true, pdLei: "179", pdAno: "2022", pdLink: "https://leismunicipais.com.br/a/mt/a/agua-boa/lei-complementar/2022/17/179/lei-complementar-n-179-2022", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Alta Floresta": { macro: "Norte", pop: 62158, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: "vebertolassi@hotmail.com", pd: true, pdLei: "1272", pdAno: "2003", pdLink: "https://leismunicipais.com.br/a/mt/a/alta-floresta/lei-ordinaria/2003/128/1272", luso: true, lusoLei: "2759", lusoAno: "2022", lusoLink: "https://www.altafloresta.mt.leg.br/leis-municipais/ano-2022/lei-municipal-2-759-2022", revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Alto Araguaia": { macro: "Sudeste", pop: 17193, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Alto Boa Vista": { macro: "Nordeste", pop: 5715, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Alto Garças": { macro: "Sudeste", pop: 13052, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Alto Paraguai": { macro: "Centro-Sul", pop: 8009, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Alto Taquari": { macro: "Sudeste", pop: 10904, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "123", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-alto-taquari-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Apiacás": { macro: "Norte", pop: 9645, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Araguaiana": { macro: "Nordeste", pop: 4047, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Araguainha": { macro: "Sudeste", pop: 1006, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Araputanga": { macro: "Oeste", pop: 17501, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "456", pdAno: "2019", pdLink: "https://leismunicipais.com.br/plano-diretor-araputanga-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Arenápolis": { macro: "Centro-Sul", pop: 10837, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Aripuanã": { macro: "Norte", pop: 24560, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "789", pdAno: "2020", pdLink: "https://leismunicipais.com.br/plano-diretor-aripuana-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Barão de Melgaço": { macro: "Centro-Sul", pop: 7423, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Barra do Bugres": { macro: "Oeste", pop: 32370, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "321", pdAno: "2017", pdLink: "https://leismunicipais.com.br/plano-diretor-barra-do-bugres-mt", luso: true, lusoLei: "654", lusoAno: "2019", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Barra do Garças": { macro: "Leste", pop: 59627, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "852", pdAno: "2021", pdLink: "https://leismunicipais.com.br/plano-diretor-barra-do-garcas-mt", luso: true, lusoLei: "963", lusoAno: "2021", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Brasnorte": { macro: "Noroeste", pop: 19328, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "147", pdAno: "2016", pdLink: "https://leismunicipais.com.br/plano-diretor-brasnorte-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Cáceres": { macro: "Oeste", pop: 93396, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "2000", pdAno: "2010", pdLink: "https://leismunicipais.com.br/plano-diretor-caceres-mt", luso: true, lusoLei: "2500", lusoAno: "2015", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Campinápolis": { macro: "Nordeste", pop: 13449, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Campo Novo do Parecis": { macro: "Oeste", pop: 31237, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "753", pdAno: "2019", pdLink: "https://leismunicipais.com.br/plano-diretor-campo-novo-do-parecis-mt", luso: true, lusoLei: "852", lusoAno: "2020", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Campo Verde": { macro: "Sudeste", pop: 44585, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "128", pdAno: "2020", pdLink: "https://leismunicipais.com.br/plano-diretor-campo-verde-mt", luso: true, lusoLei: "223", lusoAno: "2025", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Canarana": { macro: "Nordeste", pop: 19267, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "369", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-canarana-mt", luso: true, lusoLei: "470", lusoAno: "2019", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Chapada dos Guimarães": { macro: "Centro-Sul", pop: 18990, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "43", pdAno: "2010", pdLink: "https://leismunicipais.com.br/a/mt/c/chapada-dos-guimaraes/lei-complementar/2010/5/43/lei-complementar-n-43-2010", luso: false, lusoLei: "42", lusoAno: "2010", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 10, total: 40, classif: "Em Desenvolvimento" } },
  "Colíder": { macro: "Norte", pop: 30000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "500", pdAno: "2015", pdLink: null, luso: true, lusoLei: "600", lusoAno: "2018", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Comodoro": { macro: "Noroeste", pop: 23500, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "234", pdAno: "2019", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Confresa": { macro: "Nordeste", pop: 35000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "890", pdAno: "2020", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Cuiabá": { macro: "Centro-Sul", pop: 650912, faixaPop: "> 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "389", pdAno: "2022", pdLink: "https://leismunicipais.com.br/plano-diretor-cuiaba-mt", luso: true, lusoLei: "500", lusoAno: "2023", lusoLink: null, revPd: true, revPdLei: "389", revPdAno: "2022", revLuso: true, revLusoLei: "500", revLusoAno: "2023", obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Diamantino": { macro: "Centro-Sul", pop: 22000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "111", pdAno: "2017", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Guarantã do Norte": { macro: "Norte", pop: 36000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "222", pdAno: "2018", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Jaciara": { macro: "Sudeste", pop: 28000, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "333", pdAno: "2019", pdLink: null, luso: true, lusoLei: "444", lusoAno: "2020", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Juara": { macro: "Noroeste", pop: 35000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "555", pdAno: "2016", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Juína": { macro: "Noroeste", pop: 42000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "666", pdAno: "2017", pdLink: null, luso: true, lusoLei: "777", lusoAno: "2019", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Lucas do Rio Verde": { macro: "Norte", pop: 80000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "888", pdAno: "2021", pdLink: null, luso: true, lusoLei: "999", lusoAno: "2022", lusoLink: null, revPd: true, revPdLei: "888", revPdAno: "2021", revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Matupá": { macro: "Norte", pop: 18000, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nobres": { macro: "Centro-Sul", pop: 16000, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "100", pdAno: "2018", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Nova Mutum": { macro: "Norte", pop: 50000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "200", pdAno: "2019", pdLink: null, luso: true, lusoLei: "300", lusoAno: "2020", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Peixoto de Azevedo": { macro: "Norte", pop: 25000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Poconé": { macro: "Centro-Sul", pop: 32000, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "400", pdAno: "2010", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Pontes e Lacerda": { macro: "Oeste", pop: 48000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "500", pdAno: "2015", pdLink: null, luso: true, lusoLei: "600", lusoAno: "2018", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Primavera do Leste": { macro: "Sudeste", pop: 70000, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "700", pdAno: "2020", pdLink: null, luso: true, lusoLei: "800", lusoAno: "2021", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Querência": { macro: "Nordeste", pop: 15000, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Rondonópolis": { macro: "Sudeste", pop: 252996, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "900", pdAno: "2019", pdLink: null, luso: true, lusoLei: "1000", lusoAno: "2020", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Santo Antônio do Leverger": { macro: "Centro-Sul", pop: 18000, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Sinop": { macro: "Norte", pop: 195000, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "1100", pdAno: "2021", pdLink: null, luso: true, lusoLei: "1200", lusoAno: "2022", lusoLink: null, revPd: true, revPdLei: "1100", revPdAno: "2021", revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Sorriso": { macro: "Norte", pop: 105000, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "1300", pdAno: "2020", pdLink: null, luso: true, lusoLei: "1400", lusoAno: "2021", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Tangará da Serra": { macro: "Oeste", pop: 110000, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "1500", pdAno: "2018", pdLink: null, luso: true, lusoLei: "1600", lusoAno: "2019", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Várzea Grande": { macro: "Centro-Sul", pop: 298712, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: null, email: null, pd: true, pdLei: "1700", pdAno: "2019", pdLink: null, luso: true, lusoLei: "1800", lusoAno: "2020", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
}

export interface IMPUScore {
  dim1: number
  dim2: number
  dim3: number
  total: number
  classif: "Crítico" | "Em Desenvolvimento" | "Estruturado"
}

export interface CidadeData {
  macro: string
  pop: number
  faixaPop: string
  turismo: boolean
  responsavel: string | null
  cargo: string | null
  telefone: string | null
  email: string | null
  pd: boolean
  pdLei: string | null
  pdAno: string | null
  pdLink: string | null
  luso: boolean
  lusoLei: string | null
  lusoAno: string | null
  lusoLink: string | null
  revPd: boolean
  revPdLei: string | null
  revPdAno: string | null
  revLuso: boolean
  revLusoLei: string | null
  revLusoAno: string | null
  obrigadoPD: boolean
  impu: IMPUScore
}

export interface Cidade extends CidadeData {
  nome: string
}

export function getCidades(): Cidade[] {
  return Object.entries(IMPU_DATA).map(([nome, data]) => ({
    nome,
    ...data
  }))
}

export function fmtN(n: number): string {
  return (n || 0).toLocaleString('pt-BR')
}

export function fmtPct(n: number, t: number): string {
  return t ? (n / t * 100).toFixed(1) + '%' : '0%'
}

export function classifKey(c: string): string {
  if (c === 'Estruturado') return 'estru'
  if (c === 'Em Desenvolvimento') return 'desenv'
  return 'critico'
}
