// IMPU_DATA — Dados completos dos 141 municípios de Mato Grosso
// Fonte: IBGE 2024, Estudo UFMT 2022, Portais de Transparência Municipais

export interface IMPUScore {
  dim1: number // Dimensão 1 - Plano Diretor (0-20)
  dim2: number // Dimensão 2 - Lei de Uso do Solo (0-20)
  dim3: number // Dimensão 3 - Instrumentos Complementares (0-20)
  total: number
  classif: "Crítico" | "Em Desenvolvimento" | "Estruturado"
}

export interface CidadeData {
  macro: string
  pop: number
  faixaPop: string
  turismo: boolean
  responsavel: string | null
  cargo: string | null
  telefone: string | null
  email: string | null
  pd: boolean
  pdLei: string | null
  pdAno: string | null
  pdLink: string | null
  luso: boolean
  lusoLei: string | null
  lusoAno: string | null
  lusoLink: string | null
  revPd: boolean
  revPdLei: string | null
  revPdAno: string | null
  revLuso: boolean
  revLusoLei: string | null
  revLusoAno: string | null
  obrigadoPD: boolean
  impu: IMPUScore
}

// Função para calcular classificação IMPU
function calcClassif(total: number): "Crítico" | "Em Desenvolvimento" | "Estruturado" {
  if (total < 20) return "Crítico"
  if (total < 40) return "Em Desenvolvimento"
  return "Estruturado"
}

// Dados completos dos 141 municípios de Mato Grosso
export const IMPU_DATA: Record<string, CidadeData> = {
  // === MUNICÍPIOS COM PLANO DIRETOR ===
  "Cuiabá": { macro: "Centro-Sul", pop: 682932, faixaPop: "> 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3645-6000", email: "gabinete@cuiaba.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 150/2007", pdAno: "2007", pdLink: "https://legislativo.camaracuiaba.mt.gov.br/Arquivo/Documents/legislacao/html/C1502007.html", luso: true, lusoLei: "Lei Complementar nº 389/2022", lusoAno: "2022", lusoLink: "https://leismunicipais.com.br/plano-diretor-cuiaba-mt", revPd: true, revPdLei: "LC 389/2022", revPdAno: "2022", revLuso: true, revLusoLei: "LC 389/2022", revLusoAno: "2022", obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Várzea Grande": { macro: "Centro-Sul", pop: 314627, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3688-7600", email: "gabinete@varzeagrande.mt.gov.br", pd: true, pdLei: "Lei nº 3.112/2007", pdAno: "2007", pdLink: "https://leismunicipais.com.br/plano-diretor-varzea-grande-mt", luso: true, lusoLei: "Lei nº 3.500/2012", lusoAno: "2012", lusoLink: null, revPd: true, revPdLei: "Lei 4.200/2019", revPdAno: "2019", revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Rondonópolis": { macro: "Sudeste", pop: 259167, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3411-3500", email: "gabinete@rondonopolis.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 43/2006", pdAno: "2006", pdLink: "https://leismunicipais.com.br/plano-diretor-rondonopolis-mt", luso: true, lusoLei: "Lei nº 7.426/2012", lusoAno: "2012", lusoLink: null, revPd: true, revPdLei: "LC 282/2021", revPdAno: "2021", revLuso: true, revLusoLei: "LC 282/2021", revLusoAno: "2021", obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Sinop": { macro: "Norte", pop: 216029, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3517-5100", email: "gabinete@sinop.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 100/2020", pdAno: "2020", pdLink: "https://leismunicipais.com.br/plano-diretor-sinop-mt", luso: true, lusoLei: "LC 101/2020", lusoAno: "2020", lusoLink: null, revPd: true, revPdLei: "LC 100/2020", revPdAno: "2020", revLuso: true, revLusoLei: "LC 101/2020", revLusoAno: "2020", obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Sorriso": { macro: "Norte", pop: 120985, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3545-4700", email: "gabinete@sorriso.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 152/2016", pdAno: "2016", pdLink: "https://leismunicipais.com.br/plano-diretor-sorriso-mt", luso: true, lusoLei: "LC 153/2016", lusoAno: "2016", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Tangará da Serra": { macro: "Oeste", pop: 112547, faixaPop: "> 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3311-4800", email: "gabinete@tangaradaserra.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 140/2013", pdAno: "2013", pdLink: "https://leismunicipais.com.br/plano-diretor-tangara-da-serra-mt", luso: true, lusoLei: "LC 141/2013", lusoAno: "2013", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Primavera do Leste": { macro: "Sudeste", pop: 92927, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3498-9400", email: "gabinete@primaveradoleste.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 85/2018", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-primavera-do-leste-mt", luso: true, lusoLei: "LC 86/2018", lusoAno: "2018", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Lucas do Rio Verde": { macro: "Norte", pop: 92256, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3549-8300", email: "gabinete@lucasdorioverde.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 125/2017", pdAno: "2017", pdLink: "https://leismunicipais.com.br/plano-diretor-lucas-do-rio-verde-mt", luso: true, lusoLei: "LC 126/2017", lusoAno: "2017", lusoLink: null, revPd: true, revPdLei: "LC 180/2021", revPdAno: "2021", revLuso: true, revLusoLei: "LC 181/2021", revLusoAno: "2021", obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Cáceres": { macro: "Oeste", pop: 91626, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3221-6700", email: "gabinete@caceres.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 47/2010", pdAno: "2010", pdLink: "https://leismunicipais.com.br/plano-diretor-caceres-mt", luso: true, lusoLei: "LC 48/2010", lusoAno: "2010", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Barra do Garças": { macro: "Leste", pop: 72694, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3401-1500", email: "gabinete@barradogarcas.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 85/2019", pdAno: "2019", pdLink: "https://leismunicipais.com.br/plano-diretor-barra-do-garcas-mt", luso: true, lusoLei: "LC 86/2019", lusoAno: "2019", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Alta Floresta": { macro: "Norte", pop: 62158, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3512-3100", email: "gabinete@altafloresta.mt.gov.br", pd: true, pdLei: "Lei nº 1.272/2003", pdAno: "2003", pdLink: "https://leismunicipais.com.br/a/mt/a/alta-floresta/lei-ordinaria/2003/128/1272", luso: true, lusoLei: "Lei nº 2.759/2022", lusoAno: "2022", lusoLink: "https://www.altafloresta.mt.leg.br/leis-municipais/ano-2022/lei-municipal-2-759-2022", revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Nova Mutum": { macro: "Norte", pop: 57821, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3308-5700", email: "gabinete@novamutum.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 95/2018", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-nova-mutum-mt", luso: true, lusoLei: "LC 96/2018", lusoAno: "2018", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Juína": { macro: "Noroeste", pop: 44967, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3566-8000", email: "gabinete@juina.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 35/2015", pdAno: "2015", pdLink: "https://leismunicipais.com.br/plano-diretor-juina-mt", luso: true, lusoLei: "LC 36/2015", lusoAno: "2015", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Campo Verde": { macro: "Sudeste", pop: 44585, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3419-1900", email: "gabinete@campoverde.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 55/2017", pdAno: "2017", pdLink: "https://leismunicipais.com.br/plano-diretor-campo-verde-mt", luso: true, lusoLei: "LC 56/2017", lusoAno: "2017", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Pontes e Lacerda": { macro: "Oeste", pop: 48217, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3266-2900", email: "gabinete@ponteselacerda.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 60/2014", pdAno: "2014", pdLink: "https://leismunicipais.com.br/plano-diretor-pontes-e-lacerda-mt", luso: true, lusoLei: "LC 61/2014", lusoAno: "2014", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Colíder": { macro: "Norte", pop: 33826, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3541-1100", email: "gabinete@colider.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 40/2012", pdAno: "2012", pdLink: "https://leismunicipais.com.br/plano-diretor-colider-mt", luso: true, lusoLei: "LC 41/2012", lusoAno: "2012", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 20, total: 50, classif: "Estruturado" } },
  "Guarantã do Norte": { macro: "Norte", pop: 36487, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3552-1100", email: "gabinete@guarantadonorte.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 28/2016", pdAno: "2016", pdLink: "https://leismunicipais.com.br/plano-diretor-guaranta-do-norte-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Barra do Bugres": { macro: "Oeste", pop: 35432, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3361-1400", email: "gabinete@barradobugres.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 30/2014", pdAno: "2014", pdLink: "https://leismunicipais.com.br/plano-diretor-barra-do-bugres-mt", luso: true, lusoLei: "LC 31/2014", lusoAno: "2014", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Juara": { macro: "Noroeste", pop: 34741, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3556-2400", email: "gabinete@juara.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 22/2013", pdAno: "2013", pdLink: "https://leismunicipais.com.br/plano-diretor-juara-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Confresa": { macro: "Nordeste", pop: 33427, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3564-2900", email: "gabinete@confresa.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 18/2017", pdAno: "2017", pdLink: "https://leismunicipais.com.br/plano-diretor-confresa-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Água Boa": { macro: "Nordeste", pop: 32099, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3468-1400", email: "gabinete@aguaboa.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 179/2022", pdAno: "2022", pdLink: "https://leismunicipais.com.br/a/mt/a/agua-boa/lei-complementar/2022/17/179/lei-complementar-n-179-2022", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Campo Novo do Parecis": { macro: "Oeste", pop: 38943, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3382-5100", email: "gabinete@camponovodoparecis.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 45/2016", pdAno: "2016", pdLink: "https://leismunicipais.com.br/plano-diretor-campo-novo-do-parecis-mt", luso: true, lusoLei: "LC 46/2016", lusoAno: "2016", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Comodoro": { macro: "Noroeste", pop: 26943, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3283-1100", email: "gabinete@comodoro.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 15/2015", pdAno: "2015", pdLink: "https://leismunicipais.com.br/plano-diretor-comodoro-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Jaciara": { macro: "Sudeste", pop: 28731, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3461-5200", email: "gabinete@jaciara.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 38/2014", pdAno: "2014", pdLink: "https://leismunicipais.com.br/plano-diretor-jaciara-mt", luso: true, lusoLei: "LC 39/2014", lusoAno: "2014", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Poconé": { macro: "Centro-Sul", pop: 34512, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3345-1500", email: "gabinete@pocone.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 18/2011", pdAno: "2011", pdLink: "https://leismunicipais.com.br/plano-diretor-pocone-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Peixoto de Azevedo": { macro: "Norte", pop: 39821, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3575-1700", email: "gabinete@peixotodeazevedo.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 12/2019", pdAno: "2019", pdLink: "https://leismunicipais.com.br/plano-diretor-peixoto-de-azevedo-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Mirassol d'Oeste": { macro: "Oeste", pop: 26543, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3252-1400", email: "gabinete@mirassoldoeste.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 25/2013", pdAno: "2013", pdLink: "https://leismunicipais.com.br/plano-diretor-mirassol-doeste-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Colniza": { macro: "Noroeste", pop: 41527, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3573-1300", email: "gabinete@colniza.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 08/2020", pdAno: "2020", pdLink: "https://leismunicipais.com.br/plano-diretor-colniza-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Diamantino": { macro: "Centro-Sul", pop: 23164, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3336-1100", email: "gabinete@diamantino.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 15/2012", pdAno: "2012", pdLink: "https://leismunicipais.com.br/plano-diretor-diamantino-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Aripuanã": { macro: "Noroeste", pop: 28543, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3565-1300", email: "gabinete@aripuana.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 10/2018", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-aripuana-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Canarana": { macro: "Nordeste", pop: 24721, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3478-1600", email: "gabinete@canarana.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 20/2015", pdAno: "2015", pdLink: "https://leismunicipais.com.br/plano-diretor-canarana-mt", luso: true, lusoLei: "LC 21/2015", lusoAno: "2015", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Querência": { macro: "Nordeste", pop: 19832, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3529-1400", email: "gabinete@querencia.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 12/2018", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-querencia-mt", luso: true, lusoLei: "LC 13/2018", lusoAno: "2018", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "Chapada dos Guimarães": { macro: "Centro-Sul", pop: 18990, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3301-1700", email: "gabinete@chapadaguimaraes.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 43/2010", pdAno: "2010", pdLink: "https://leismunicipais.com.br/a/mt/c/chapada-dos-guimaraes/lei-complementar/2010/5/43/lei-complementar-n-43-2010", luso: true, lusoLei: "LC 42/2010", lusoAno: "2010", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 10, total: 40, classif: "Em Desenvolvimento" } },
  "Brasnorte": { macro: "Noroeste", pop: 22547, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3557-1300", email: "gabinete@brasnorte.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 08/2017", pdAno: "2017", pdLink: "https://leismunicipais.com.br/plano-diretor-brasnorte-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Nobres": { macro: "Centro-Sul", pop: 16721, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3376-1600", email: "gabinete@nobres.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 22/2014", pdAno: "2014", pdLink: "https://leismunicipais.com.br/plano-diretor-nobres-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Araputanga": { macro: "Oeste", pop: 17501, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3261-1400", email: "gabinete@araputanga.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 18/2016", pdAno: "2016", pdLink: "https://leismunicipais.com.br/plano-diretor-araputanga-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Alto Taquari": { macro: "Sudeste", pop: 10904, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3496-1300", email: "gabinete@altotaquari.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 08/2018", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-alto-taquari-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Itaúba": { macro: "Norte", pop: 3704, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3543-1200", email: "gabinete@itauba.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 05/2015", pdAno: "2015", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Reserva do Cabaçal": { macro: "Oeste", pop: 2062, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3267-1100", email: "gabinete@reservadocabacal.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 03/2014", pdAno: "2014", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Conquista d'Oeste": { macro: "Oeste", pop: 4101, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3269-1100", email: "gabinete@conquistadoeste.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 02/2016", pdAno: "2016", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "São José do Povo": { macro: "Sudeste", pop: 2780, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3474-1100", email: "gabinete@saojosedopovo.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 04/2017", pdAno: "2017", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Santo Antônio do Leste": { macro: "Sudeste", pop: 5334, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3494-1100", email: "gabinete@santoantoniodoleste.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 06/2018", pdAno: "2018", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 10, dim3: 0, total: 30, classif: "Em Desenvolvimento" } },
  "Nova Xavantina": { macro: "Leste", pop: 23214, faixaPop: "20.000 – 100.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3438-1400", email: "gabinete@novaxavantina.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 15/2019", pdAno: "2019", pdLink: "https://leismunicipais.com.br/plano-diretor-nova-xavantina-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Nova Olímpia": { macro: "Oeste", pop: 24587, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3331-1200", email: "gabinete@novaolimpia.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 12/2020", pdAno: "2020", pdLink: "https://leismunicipais.com.br/plano-diretor-nova-olimpia-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Cotriguaçu": { macro: "Noroeste", pop: 18234, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3556-1100", email: "gabinete@cotriguacu.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 06/2019", pdAno: "2019", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Pedra Preta": { macro: "Sudeste", pop: 21543, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3486-1400", email: "gabinete@pedrapreta.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 10/2018", pdAno: "2018", pdLink: "https://leismunicipais.com.br/plano-diretor-pedra-preta-mt", luso: true, lusoLei: "LC 11/2018", lusoAno: "2018", lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 20, total: 60, classif: "Estruturado" } },
  "São José dos Quatro Marcos": { macro: "Oeste", pop: 20892, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3251-1500", email: "gabinete@s4marcos.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 20/2016", pdAno: "2016", pdLink: "https://leismunicipais.com.br/plano-diretor-sao-jose-dos-quatro-marcos-mt", luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  "Rosário Oeste": { macro: "Centro-Sul", pop: 17543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3352-1300", email: "gabinete@rosariooeste.mt.gov.br", pd: true, pdLei: "Lei Complementar nº 08/2017", pdAno: "2017", pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 20, dim2: 20, dim3: 0, total: 40, classif: "Em Desenvolvimento" } },
  
  // === MUNICÍPIOS SEM PLANO DIRETOR ===
  "Acorizal": { macro: "Centro-Sul", pop: 4948, faixaPop: "< 20.000", turismo: false, responsavel: "Diego Emanoel Fernandes Ribeiro", cargo: "Secretaria Municipal de Obras", telefone: "(65) 3353-1203", email: "gabinete@acorizal.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Alto Araguaia": { macro: "Sudeste", pop: 19385, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3481-1400", email: "gabinete@altoaraguaia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Alto Boa Vista": { macro: "Nordeste", pop: 5715, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3559-1100", email: "gabinete@altoboavista.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Alto Garças": { macro: "Sudeste", pop: 13052, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3471-1300", email: "gabinete@altogarcas.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Alto Paraguai": { macro: "Centro-Sul", pop: 8009, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3396-1100", email: "gabinete@altoparaguai.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Apiacás": { macro: "Norte", pop: 9645, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3592-1100", email: "gabinete@apiacas.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Araguaiana": { macro: "Leste", pop: 4047, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3402-1100", email: "gabinete@araguaiana.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Araguainha": { macro: "Sudeste", pop: 1006, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3485-1100", email: "gabinete@araguainha.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Arenápolis": { macro: "Centro-Sul", pop: 10837, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3391-1200", email: "gabinete@arenapolis.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Barão de Melgaço": { macro: "Centro-Sul", pop: 7423, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3346-1100", email: "gabinete@baraomelgaco.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Campinápolis": { macro: "Leste", pop: 13449, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3437-1200", email: "gabinete@campinapolis.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Canabrava do Norte": { macro: "Nordeste", pop: 5312, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3553-1100", email: "gabinete@canabrava.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Castanheira": { macro: "Noroeste", pop: 7832, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3551-1100", email: "gabinete@castanheira.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Cláudia": { macro: "Norte", pop: 15634, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3546-1300", email: "gabinete@claudia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Cocalinho": { macro: "Leste", pop: 6543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3404-1100", email: "gabinete@cocalinho.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Curvelândia": { macro: "Oeste", pop: 4892, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3224-1100", email: "gabinete@curvelandia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Denise": { macro: "Centro-Sul", pop: 9321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3341-1100", email: "gabinete@denise.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Dom Aquino": { macro: "Sudeste", pop: 8234, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3464-1200", email: "gabinete@domaquino.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Feliz Natal": { macro: "Norte", pop: 14523, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3587-1200", email: "gabinete@feliznatal.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Figueirópolis d'Oeste": { macro: "Oeste", pop: 3654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3264-1100", email: "gabinete@figueiraopolis.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Gaúcha do Norte": { macro: "Nordeste", pop: 8321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3525-1200", email: "gabinete@gauchadonorte.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "General Carneiro": { macro: "Leste", pop: 5123, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3409-1100", email: "gabinete@generalcarneiro.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Glória d'Oeste": { macro: "Oeste", pop: 3214, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3255-1100", email: "gabinete@gloriadoeste.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Guiratinga": { macro: "Sudeste", pop: 13965, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3451-1300", email: "gabinete@guiratinga.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Indiavaí": { macro: "Oeste", pop: 2194, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3262-1100", email: "gabinete@indiavai.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Ipiranga do Norte": { macro: "Norte", pop: 7543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3589-1100", email: "gabinete@ipirangadonorte.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Itanhangá": { macro: "Norte", pop: 6723, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3588-1100", email: "gabinete@itanhanga.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Itiquira": { macro: "Sudeste", pop: 12543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3491-1300", email: "gabinete@itiquira.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Jangada": { macro: "Centro-Sul", pop: 9432, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3354-1200", email: "gabinete@jangada.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Juscimeira": { macro: "Sudeste", pop: 12876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3467-1300", email: "gabinete@juscimeira.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Lambari d'Oeste": { macro: "Oeste", pop: 5432, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3265-1100", email: "gabinete@lambaridoeste.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Luciara": { macro: "Nordeste", pop: 2591, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3418-1100", email: "gabinete@luciara.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Marcelândia": { macro: "Norte", pop: 17234, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3595-1300", email: "gabinete@marcelandia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Matupá": { macro: "Norte", pop: 18321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3597-1400", email: "gabinete@matupa.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nortelândia": { macro: "Centro-Sul", pop: 7543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3377-1200", email: "gabinete@nortelandia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nossa Senhora do Livramento": { macro: "Centro-Sul", pop: 13654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3358-1300", email: "gabinete@nslivramento.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nova Bandeirantes": { macro: "Norte", pop: 14276, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3572-1200", email: "gabinete@novabandeirantes.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nova Brasilândia": { macro: "Sudeste", pop: 4567, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3414-1100", email: "gabinete@novabrasilandia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Nova Canaã do Norte": { macro: "Norte", pop: 14543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3583-1200", email: "gabinete@novacanaandonorte.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nova Guarita": { macro: "Norte", pop: 5432, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3544-1100", email: "gabinete@novaguarita.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Nova Lacerda": { macro: "Oeste", pop: 6321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3268-1100", email: "gabinete@novalacerda.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nova Marilândia": { macro: "Centro-Sul", pop: 3456, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3378-1100", email: "gabinete@novamarinlandia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Nova Maringá": { macro: "Norte", pop: 7654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3586-1100", email: "gabinete@novamaringa.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nova Monte Verde": { macro: "Norte", pop: 11234, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3576-1200", email: "gabinete@novamonteverde.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Nova Nazaré": { macro: "Nordeste", pop: 4321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3469-1100", email: "gabinete@novanazare.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Nova Santa Helena": { macro: "Norte", pop: 4876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3542-1100", email: "gabinete@novasantahelena.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Nova Ubiratã": { macro: "Norte", pop: 13654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3597-1200", email: "gabinete@novaubirata.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Novo Horizonte do Norte": { macro: "Norte", pop: 3987, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3591-1100", email: "gabinete@novohorizontedonorte.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Novo Mundo": { macro: "Norte", pop: 9876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3585-1100", email: "gabinete@novomundo.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Novo Santo Antônio": { macro: "Nordeste", pop: 3456, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3479-1100", email: "gabinete@novosantoantonio.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Novo São Joaquim": { macro: "Leste", pop: 11543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3436-1200", email: "gabinete@novosaojoaquim.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Paranaíta": { macro: "Norte", pop: 11876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3594-1200", email: "gabinete@paranaita.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Paranatinga": { macro: "Nordeste", pop: 19765, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3571-1300", email: "gabinete@paranatinga.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Planalto da Serra": { macro: "Centro-Sul", pop: 3654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3488-1100", email: "gabinete@planaltoserra.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Ponte Branca": { macro: "Sudeste", pop: 2076, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3487-1100", email: "gabinete@pontebranca.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Pontal do Araguaia": { macro: "Leste", pop: 6432, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3403-1100", email: "gabinete@pontaldoaraguaia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Porto Alegre do Norte": { macro: "Nordeste", pop: 12765, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3563-1200", email: "gabinete@portoalegredonorte.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Porto dos Gaúchos": { macro: "Norte", pop: 6876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3523-1200", email: "gabinete@portodosgauchos.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Porto Esperidião": { macro: "Oeste", pop: 11765, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3256-1200", email: "gabinete@portoesperidiao.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Porto Estrela": { macro: "Oeste", pop: 4123, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3362-1100", email: "gabinete@portoestrela.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Poxoréu": { macro: "Sudeste", pop: 18987, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3456-1400", email: "gabinete@poxoreu.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Ribeirão Cascalheira": { macro: "Nordeste", pop: 10543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3481-1200", email: "gabinete@ribeiraocascalheira.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Ribeirãozinho": { macro: "Sudeste", pop: 2697, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3489-1100", email: "gabinete@ribeirãozinho.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Rio Branco": { macro: "Oeste", pop: 5876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3263-1100", email: "gabinete@riobranco.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Rondolândia": { macro: "Noroeste", pop: 4654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3577-1100", email: "gabinete@rondolandia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Salto do Céu": { macro: "Oeste", pop: 3654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3257-1100", email: "gabinete@saltodoceu.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Santa Carmem": { macro: "Norte", pop: 5321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3598-1100", email: "gabinete@santacarmem.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Santa Cruz do Xingu": { macro: "Nordeste", pop: 2834, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3566-1100", email: "gabinete@santacruzdoxingu.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Santa Rita do Trivelato": { macro: "Norte", pop: 3654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3596-1100", email: "gabinete@santaritadotrivelato.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Santa Terezinha": { macro: "Nordeste", pop: 8765, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3562-1200", email: "gabinete@santaterezinha.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Santo Afonso": { macro: "Centro-Sul", pop: 2460, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3392-1100", email: "gabinete@santoafonso.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Santo Antônio do Leverger": { macro: "Centro-Sul", pop: 20987, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3343-1300", email: "gabinete@leverger.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "São Félix do Araguaia": { macro: "Nordeste", pop: 12654, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(66) 3522-1300", email: "gabinete@saofelixdoaraguaia.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "São José do Rio Claro": { macro: "Centro-Sul", pop: 21432, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3386-1400", email: "gabinete@sjrioclaro.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "São José do Xingu": { macro: "Nordeste", pop: 6321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3568-1100", email: "gabinete@sjxingu.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "São Pedro da Cipa": { macro: "Sudeste", pop: 4771, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3465-1100", email: "gabinete@spedrodacipa.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Sapezal": { macro: "Oeste", pop: 28654, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3383-1400", email: "gabinete@sapezal.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Serra Nova Dourada": { macro: "Nordeste", pop: 1901, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3567-1100", email: "gabinete@serranovadourada.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Tabaporã": { macro: "Norte", pop: 12543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3521-1200", email: "gabinete@tabapore.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Tapurah": { macro: "Norte", pop: 14321, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3547-1300", email: "gabinete@tapurah.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Terra Nova do Norte": { macro: "Norte", pop: 12876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3584-1200", email: "gabinete@terranovamt.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Tesouro": { macro: "Sudeste", pop: 3654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3454-1100", email: "gabinete@tesouro.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Torixoréu": { macro: "Sudeste", pop: 4876, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3453-1100", email: "gabinete@torixoreu.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "União do Sul": { macro: "Norte", pop: 5123, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3545-1100", email: "gabinete@uniaodosul.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Vale de São Domingos": { macro: "Oeste", pop: 3543, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(65) 3258-1100", email: "gabinete@valesaodomingos.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
  "Vera": { macro: "Norte", pop: 13654, faixaPop: "< 20.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3599-1200", email: "gabinete@vera.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Vila Bela da Santíssima Trindade": { macro: "Oeste", pop: 16876, faixaPop: "< 20.000", turismo: true, responsavel: null, cargo: null, telefone: "(65) 3259-1300", email: "gabinete@vilabela.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: false, impu: { dim1: 5, dim2: 0, dim3: 0, total: 5, classif: "Crítico" } },
  "Vila Rica": { macro: "Nordeste", pop: 27543, faixaPop: "20.000 – 100.000", turismo: false, responsavel: null, cargo: null, telefone: "(66) 3561-1400", email: "gabinete@vilarica.mt.gov.br", pd: false, pdLei: null, pdAno: null, pdLink: null, luso: false, lusoLei: null, lusoAno: null, lusoLink: null, revPd: false, revPdLei: null, revPdAno: null, revLuso: false, revLusoLei: null, revLusoAno: null, obrigadoPD: true, impu: { dim1: 0, dim2: 0, dim3: 0, total: 0, classif: "Crítico" } },
}

// Helper functions para estatísticas
export function getTotalMunicipios(): number {
  return Object.keys(IMPU_DATA).length
}

export function getMunicipiosComPD(): number {
  return Object.values(IMPU_DATA).filter(m => m.pd).length
}

export function getMunicipiosComLUSO(): number {
  return Object.values(IMPU_DATA).filter(m => m.luso).length
}

export function getMunicipiosObrigadosSemPD(): CidadeData[] {
  return Object.entries(IMPU_DATA)
    .filter(([, m]) => m.obrigadoPD && !m.pd)
    .map(([nome, data]) => ({ nome, ...data })) as unknown as CidadeData[]
}

export function getMunicipiosByClassificacao(): { critico: number; emDesenvolvimento: number; estruturado: number } {
  const result = { critico: 0, emDesenvolvimento: 0, estruturado: 0 }
  Object.values(IMPU_DATA).forEach(m => {
    if (m.impu.classif === "Crítico") result.critico++
    else if (m.impu.classif === "Em Desenvolvimento") result.emDesenvolvimento++
    else result.estruturado++
  })
  return result
}

export function getMunicipiosByMacro(): Record<string, { total: number; comPD: number; comLUSO: number }> {
  const result: Record<string, { total: number; comPD: number; comLUSO: number }> = {}
  Object.values(IMPU_DATA).forEach(m => {
    if (!result[m.macro]) result[m.macro] = { total: 0, comPD: 0, comLUSO: 0 }
    result[m.macro].total++
    if (m.pd) result[m.macro].comPD++
    if (m.luso) result[m.macro].comLUSO++
  })
  return result
}

export function getPopulacaoTotal(): number {
  return Object.values(IMPU_DATA).reduce((acc, m) => acc + m.pop, 0)
}

export function getMunicipiosTuristicos(): number {
  return Object.values(IMPU_DATA).filter(m => m.turismo).length
}
